import { PropsWithChildren } from 'react';

import type { Metadata } from 'next';

import { sans } from '@/lib/fonts';

import { Providers } from '@/components/providers';
import Root from '@/components/root';

import '@repo/ui/globals.css';

export const metadata: Metadata = {
  title: 'Create Turborepo',
  description: 'Generated by create turbo',
};

export default function RootLayout({ children }: Readonly<PropsWithChildren>) {
  return (
    <html lang="ja" suppressHydrationWarning className={sans.variable}>
      <body>
        <Providers>
          <Root>{children}</Root>
        </Providers>
      </body>
    </html>
  );
}
